language: c

branches:
  only:
    - master
    - release

dist: trusty
sudo: required

matrix:
  include:
    - os: linux

rvm:
  - 2.2.3

install:
  - sudo apt-get install -y rpm ruby ruby-dev git
  - rvm install ruby-2.2.3
  - rvm use 2.2.3 --default
  - gem install fpm

script:
  - export PACKAGE_VERSION="`cat VERSION`"
  - export PACKAGE_ITERATION="${PACKAGE_ITERATION}${TRAVIS_BUILD_NUMBER}.`git rev-parse --short --verify HEAD^{commit}`";
  - mkdir build
  - mkdir build/bin
  - fpm -s empty -t rpm -p build/bin --name ponydep-ncurses-libs-5-compat --conflicts ponydep-ncurses-libs-5        --provides ponydep-ncurses --version "${PACKAGE_VERSION}" --iteration "${PACKAGE_ITERATION}" --description "An RPM to satisfy the ponyc dependency on ncurses" --depends "ncurses-compat-libs >= 6"
  - fpm -s empty -t rpm -p build/bin --name ponydep-ncurses-libs-5        --conflicts ponydep-ncurses-libs-5-compat --provides ponydep-ncurses --version "${PACKAGE_VERSION}" --iteration "${PACKAGE_ITERATION}" --description "An RPM to satisfy the ponyc dependency on ncurses" --depends "ncurses < 6" 

after_success:
  - sh .bintray.sh rpm "${PACKAGE_VERSION}-${PACKAGE_ITERATION}" ponydep-ncurses-libs-5
  - sh .bintray.sh rpm "${PACKAGE_VERSION}-${PACKAGE_ITERATION}" ponydep-ncurses-libs-5-compat

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - buildbot@lists.ponylang.org

deploy:
  - provider: bintray
    user: pony-buildbot-2
    file: /home/travis/build/ponylang/ponydep-ncurses/bintray_rpm_ponydep-ncurses-libs-5.yml
    on:
      branch: release
    key:
      secure: FIXME

  - provider: bintray
    user: pony-buildbot-2
    file: /home/travis/build/ponylang/ponydep-ncurses/bintray_rpm_ponydep-ncurses-libs-5-compat.yml
    on:
      branch: release
    key:
      secure: FIXME
