language: c

branches:
  only:
    - master
    - release

dist: trusty
sudo: required

matrix:
  include:
    - os: linux

rvm:
  - 2.2.3

install:
  - sudo apt-get install -y rpm ruby ruby-dev git
  - rvm install ruby-2.2.3
  - rvm use 2.2.3 --default
  - gem install fpm

script:
  - export PACKAGE_VERSION="`cat VERSION`"
  - export PACKAGE_ITERATION="${PACKAGE_ITERATION}${TRAVIS_BUILD_NUMBER}.`git rev-parse --short --verify HEAD^{commit}`";
  - mkdir build
  - mkdir build/bin
  - fpm -s empty -t rpm -p build/bin --name ponydep-ncurses-libs-5-compat --conflicts ponydep-ncurses-libs-5        --provides ponydep-ncurses --version "${PACKAGE_VERSION}" --iteration "${PACKAGE_ITERATION}" --description "An RPM to satisfy the ponyc dependency on ncurses" --depends "ncurses-compat-libs >= 6"
  - fpm -s empty -t rpm -p build/bin --name ponydep-ncurses-libs-5        --conflicts ponydep-ncurses-libs-5-compat --provides ponydep-ncurses --version "${PACKAGE_VERSION}" --iteration "${PACKAGE_ITERATION}" --description "An RPM to satisfy the ponyc dependency on ncurses" --depends "ncurses < 6" 

after_success:
  - sh .bintray.sh rpm "${PACKAGE_VERSION}-${PACKAGE_ITERATION}" ponydep-ncurses-libs-5
  - sh .bintray.sh rpm "${PACKAGE_VERSION}-${PACKAGE_ITERATION}" ponydep-ncurses-libs-5-compat

notifications:
  email:
    on_success: always
    on_failure: always
    recipients:
    - buildbot@lists.ponylang.org

deploy:
  - provider: bintray
    user: pony-buildbot-2
    file: /home/travis/build/ponylang/ponydep-ncurses/bintray_rpm_ponydep-ncurses-libs-5.yml
    on:
      branch: release
    key:
      secure: "BMo2OoTA0zyDbrI6qYIHd/qXeqPn7uEdbiPykr7gt8JohhPrKnE01dbb3PBiHf/wQ5llpZ7JqARkjV5Na0Yakazn9aCH52tZxH30Xjz8Y3A0TS953pTjXPcm9wdMV3xK25st14nLRAHOJhD7u1uswgUkvACArJl3ewzdTUNW8bBvZFn0YqIbxugMakZzjTQV9e9mqqtB2DBVTH+AXsgQCz7a6aPJcRiKaCgsyzsPTki7hzlTS904fyDM7tMAlh8md54MABdP6DqFdBZKn4x8twuP0E7mqvYrXm9gqw16YBk/CmcVH0v/XEayWUIwOzW8nkVC5WKuWQtP+8LjiuzgJmQkERiUt/dg4l/jd6WpDz8Tu9sW9WnQQLA+5ztLBkCx6a9W2Y/ZGK6dZjv3gTpzO5haHj6QLsQmhbruZVTLO5DJUsVMVNEfD0AxBx38v7DA6NJhsNypgk4KtxwBw8guSv1g+oC2CJ5Vjgv6aPb8kZt4b3km+vFwFqf3aTErdPOG2Ud4gRfwQAzXluszRLyAT3tdeSxp5m4/QeOfCoR1U6rM2fZtYJNPWac5yq8PErFRXusHtvj3Bh9b3VshLnXpFNJZQQxpXSNBewg+WMWg9a3O4EcG17N7EWaIFsapdDNBsOjcJ6YfvzPqnRgb7FCRg5NXbtbG0wz02WW+LCH6Mfw="

  - provider: bintray
    user: pony-buildbot-2
    file: /home/travis/build/ponylang/ponydep-ncurses/bintray_rpm_ponydep-ncurses-libs-5-compat.yml
    on:
      branch: release
    key:
      secure: "BMo2OoTA0zyDbrI6qYIHd/qXeqPn7uEdbiPykr7gt8JohhPrKnE01dbb3PBiHf/wQ5llpZ7JqARkjV5Na0Yakazn9aCH52tZxH30Xjz8Y3A0TS953pTjXPcm9wdMV3xK25st14nLRAHOJhD7u1uswgUkvACArJl3ewzdTUNW8bBvZFn0YqIbxugMakZzjTQV9e9mqqtB2DBVTH+AXsgQCz7a6aPJcRiKaCgsyzsPTki7hzlTS904fyDM7tMAlh8md54MABdP6DqFdBZKn4x8twuP0E7mqvYrXm9gqw16YBk/CmcVH0v/XEayWUIwOzW8nkVC5WKuWQtP+8LjiuzgJmQkERiUt/dg4l/jd6WpDz8Tu9sW9WnQQLA+5ztLBkCx6a9W2Y/ZGK6dZjv3gTpzO5haHj6QLsQmhbruZVTLO5DJUsVMVNEfD0AxBx38v7DA6NJhsNypgk4KtxwBw8guSv1g+oC2CJ5Vjgv6aPb8kZt4b3km+vFwFqf3aTErdPOG2Ud4gRfwQAzXluszRLyAT3tdeSxp5m4/QeOfCoR1U6rM2fZtYJNPWac5yq8PErFRXusHtvj3Bh9b3VshLnXpFNJZQQxpXSNBewg+WMWg9a3O4EcG17N7EWaIFsapdDNBsOjcJ6YfvzPqnRgb7FCRg5NXbtbG0wz02WW+LCH6Mfw="
